apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ""
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b1FodWN6ZC83YU9vQUxY
        c3lNbUlQRDhaNkZTeEFxM0NYeUZqdjlFd0d3CnZ2dCtzdkdOVktBWEFERDZhU1lS
        dVBhVmh3TCtXb2xGdWhXTTFOYXFuYUUKLS0tIFI5Q1grdjlPMEpHVlVsek4xbUlU
        RjgzYmNvTlMvRm9jSE5vc1krUDd4QUEKNC+csB/OWrZ6yOdc18/GjGHH0K4utnFS
        nzBO2kkcqwZ6U8FUoTwt54buip1G/HCWrotFb+Yo1lHT60g0Y8AZlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T09:00:08Z"
  mac: ENC[AES256_GCM,data:lJtOb1OtWOWstaL8BSpTJPsQ28W/pNa2oinlpUXJe8DqdAwA1cyOSg/zdfZfAFhgsJwioZgDNJLxzicUK/JmrmQA1M/l/FyEIYwptWZFbanhIH9vB+Y78aAzgIxaqA6zUbqGMo7SLh5/lAa2PLTaVbsPbQkGABM/uCNn04hcIuM=,iv:ZEya3P775cJ/l+IEff3V361cl9obJP7YBBksJ5fkKt4=,tag:5ZDJa1qXWSl840E/l3/gCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
