apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:AE92slw4f3UX2w8v1SUuB2i/N3ZJsPrrF0L/hl0TO8eO5wxnQe3kcg==,iv:gxetCPnNNVwnFX9Yq1xovRttcj7DBXsKcELwISRX1Zs=,tag:ReW9nITaCAdO04dju2RVuA==,type:str]
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY2kxTnl3ZG11UENRb05E
        Qk5nTmdGbG9QbzJ2TTZpR1NlMUNyOVpOZlU0CnljUTAwSGpZMVJSakM3ZHlWSEZZ
        MzA3SEJHdTJwY1VrUDdKOXQ1TFNabTAKLS0tIEdoWk8xK1BTdHloR0hmVkFFNjJy
        cktaL1BPSk1sYTdROEs0K0gxMU5hUFkKvsnOQNwmvaMaUCFADoLlUBSB9WgJxYJx
        RuObeHxFaXLpN3H+faOdDen1XCInyt47vec3619mQu07THdDptWzHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T08:46:18Z"
  mac: ENC[AES256_GCM,data:xzdQcQ6AOnPfudtrftuewsDGp7twmLb3WGHf+AAuKINM0hpmpNSSNp7bkSUpdxK5F42h2kLbv5IL0CBW/G2Zb8T3luc2IJcgm7FQUyaASTRErxXpTRH3q4CdoVb7v+mPMylBCA5uCfjZF4bTyfUqdg3D14w6kVyjaMhtKOcOcWE=,iv:zHluLI0PoyddCLTICFfmO3N33jvAuLDSSuv5HH+WiAg=,tag:ViAXpPaddHOhCtsoflHXfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
