apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cZtJcxmGLYozUC93hW/W,iv:Bx6Gze85EB5QPVFaJukYoK598W9omcoLQpnXRyyj7XA=,tag:aKnWMtROFJR7Ni7ks/4Bug==,type:str]
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTm1YV3hUZS9NUk05RnZ3
        RFRCT2pxWFNzVUpXS1lPVFVZczk5TUJ0VlJjCitiMzlFZDcxRHlrVTRWY1ZxLzl5
        RDNvZGxZdlRPSkhEZHAwc2YwYjA0NFEKLS0tIG9FY3ZZYThGUjlKd1RvajRoRmMz
        a3lnWm9WWHFNaTNydk1zN2ZZd0RBSTQKF5X6PnDpR8H2sluRjzVLy52I5KaIz46l
        mfrbegt5v7Xufv+RrwRrFxhI3AckJd3k3xvYKesz87pBDLd7tv5jpA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T08:46:18Z"
  mac: ENC[AES256_GCM,data:T7q/vxjIzu/TnkiBZiHXGvXbR2tub4zA0N9oU+52Kv2xyYNlaTCEJbw30h3Q4gbDXeKmdDYpPVeJZSoADmkNmtJwtgAxMI9JCwocLUktecOZiulhbh/Rt5v9g7qjHSbIM55Lh8SkDJqeKSa8D9ud5kBY3uI1KrzJM/rqlvZuaGs=,iv:2MBrI+HxAIYLBBIUj114JHH1UjkoXu8A31qb6MRai8k=,tag:l905KaTNu0YCgbcrfEY69w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
