apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3eS6Yz6sfh3iDPmtpW2kST/qIq/ZdJn0/4ONKNlXNTI=,iv:WeU2w8/Il9qVRnbOlVJesE2R6twewgCDk64DrilNt9Y=,tag:De9fnd5F6YD3vryaiztJGg==,type:str]
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc21idXA2NTkxeFRiczUx
        eEkyN2o3SUpaS1JUbGFQNXhLSXdqVVlRZFVvCmFkS1IxNCtYdWdPUDdCMmExdVE4
        NWM0YTdYWFFSUlQ2UmZaTkRsbWQ1cWsKLS0tIFlBazNXMVk3d0c2SUoyVSs1MGhs
        SnZWT25obHJnWnpDMEVRSUEwSUxLNzQKarLSu25FYvlwfITKD9UgsqzQfpmu76a9
        uKGdniT9cH6ivvJYjCeEEZxBTiro5V+J1MuhpamfJV2p+CWZMYDAHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T08:46:18Z"
  mac: ENC[AES256_GCM,data:ldtMuFB4lsFdDAhBvcGFzYgQ1KTcojMf3yDPMtv4F/4c7/U9N4HtRioVeo75751z45EAm22yvSRPVhubl/5z4y0amVJI3rLTV8Nt5zKz2e+VLjcOHHomWkMCqIxzqmp0akn1Rl+mCbC2y2QP905k06irRM5kHWWz6Y54yyI3o/Y=,iv:0h2BoBpWOyUVHDC7fnvhypY+Hf8gM10CXvLZ4J+6fRA=,tag:DzjKO3fBaH8vm3KF51Nj0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
