apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rruLTAGzHMgD6raqU/4/Z9OVHkv/oXuKkvsOZMzF077JAzw4OMYxWZncqaqdzfCR7fKTv0npIx5YxOQS+hZeJleqRC+xSOgHe8MaFL0nUDy/rh5K2s8qdgSCaj5JP6F00Djf7Gty4eUqDZaPvqtF0W2ctYrKHOitPfsP3XbfWmdhd+4NROh3Y37GXqvNo4J0Xa7/uKu5h12nMelgfDSeFhNdnCbniPy04KdEms7WuH0FB6TM,iv:GL5O4OAWmnPU9dgn3Oh+vh1tU50+3AEF3M6P0rQQyv0=,tag:KV2fIVOJHER6JT4QEOEXzg==,type:str]
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNjRJNFpDeVRCNy9WZytV
        RXIyc2JVNFJBTzR4T3JmcVBNNmhzYUtBWndjCkp3RU12RGVaVWUzVHFxWTQ5Nk1z
        dTJWaDlPb21rYmNTU0F3NEZ5RFRsM0EKLS0tIGMxTG1HZjUvLzZ4SGI4TUJySnhW
        NzU2ekYyeTNFRjBxcnZQdCtuWldZVTQKffelraUi8mC2518SRCzjjKi3ywJfy6Yn
        wLSvf3yDNj7Q0uogYA+qjA/CYAK8gnH5JEKblQefc6zGLSU2P4jKmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T08:46:18Z"
  mac: ENC[AES256_GCM,data:cimM17h5WQlZUWqZskEYpbsrpsDblgvBUOOrf90ULgGULux/rzRX/Xlv+nJraINKKNGodcmpKMouYvxn7G8o3Y8AEpdDCvSBkigK5xGiEYtG6uGp/VduPcEKPC6zDy8pM6r5QhFfNv2pQjCOvFinLjb2JS7Zs7KxNj2+nA0JOVc=,iv:jwu2g19QginEWbKgd0oFanEBqjqbVI0G+o1PaPL9LQo=,tag:SOYv6Fnic6B5F4QOd4bCgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
