---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: "eyJhIjoiYTAxOGI3ZDQxYzA0ODEwMThmZDJmMDQ0NjcyNDA2NjYiLCJ0IjoiNDNhZWU4ZjAtYjQ3Mi00NGZhLWI4NWItYzBmZDE2NDY1MGJmIiwicyI6ImgxMUgwR0ZRUmc4Z2t1SlF3MmhmeEI1QXdlN0tjeDluU010YkJrZk1IcjA9In0="
