apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0fIWPqi65GzG3ue0QWBjiNcpB8yCojh2YgR3IqxdfGFR0awV32xnng==,iv:CMHXp37+yOczxILRTbgtaX7BY96eObI7Vg6vRmTPPeE=,tag:hQPCIZjJCU+0F/fFmBU6Ug==,type:str]
sops:
  age:
    - recipient: age12zu058m6zxz3y7gg66spuf7uqea7av26fs3rnaq35yndg5wrep9qlcvak8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzlQUlVTd3Z4RUhIRHNs
        QklDQ053VlAxYzYxZ2c0RVJMYmZ2OE1vNkFjCmlzblVSMVEvK0txZTZpekY3V0FY
        M0d1bWowWVJtYS9DUVJRd1B1c3N1a2cKLS0tIGh5NmNicmVlcnA4SEhyZGFuek41
        am11enBUZyt2SDhaei9zbHJhdDYxVVEKg+Eh0CbwyOsEIZPmZWbs4jlWNWKVrXQn
        qMsp3by1lzh1+go3LkFkwgulfRFU2Y/kJEdKJVeA2e8ihVEEYN8HPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T08:46:18Z"
  mac: ENC[AES256_GCM,data:4p68D2HP7FZf+ng41nNpXlFddFw0pG1ZwmAsVyM3PCxKkcSxbmGzFhhqD6OejXqZUuqZ9VME8AIVFYfuA545efzEnrsFOWhd/oSnhilq5AylXb7nU4AHCsZ9VMCcpxcml1W6KfAw/EPA7wEba3outgCj6uz/DZe5o2bb82oDNwQ=,iv:jyegkvCC/1OxsVaGB8Y2W45fnc+bnP0swvi/72FhMf0=,tag:MTzJs9U0PWjZ//JobNEQVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
